### ISSUE TITLE
lydogbillede.dk

### ISSUE THREAD

**Issue by DandelionSprout** [llacb47/miscfilters#9]
Example page: `https://www.lydogbillede.dk/nyheter/square-koeber-majoritetsandel-i-tidal-for-297-millioner-dollars/?hw=1`

Fix:
```
lydogbilde.no,lydogbillede.dk##.entry-content-wrap:style(max-height: none !important; overflow: initial !important)
lydogbilde.no,lydogbillede.dk##.lbplussinfo
```

This was first brought to my attention in https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-792325426

**Comment by llacb47** [comment]
should be fixed.

**Comment by DandelionSprout** [comment]
I think you forgot to add the same entries for `lydogbilde.no`

**Comment by llacb47** [comment]
Whoops, sorry. I'll add it in a few hours

**Comment by llacb47** [comment]
https://github.com/llacb47/miscfilters/commit/737e1cf0a433cbb691b6a85ec19bf2919d14c248
